# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/Users/TEMP.PCLABS/Desktop/MIPSLite/MIPSLite.cache/wt [current_project]
set_property parent.project_path D:/Users/TEMP.PCLABS/Desktop/MIPSLite/MIPSLite.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths f:/LAB44444/Lab4/Lab4/MIPS/MIPS.cache/ip [current_project]
set_property ip_output_repo f:/LAB44444/Lab4/Lab4/MIPS/MIPS.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib -sv {
  D:/Users/TEMP.PCLABS/Desktop/MIPSLite/MIPSLite.srcs/sources_1/new/dmem.sv
  D:/Users/TEMP.PCLABS/Desktop/MIPSLite/MIPSLite.srcs/sources_1/new/imem.sv
  D:/Users/TEMP.PCLABS/Desktop/MIPSLite/MIPSLite.srcs/sources_1/new/mips.sv
  D:/Users/TEMP.PCLABS/Desktop/MIPSLite/MIPSLite.srcs/sources_1/new/top.sv
}
synth_design -top top -part xc7a35tcpg236-1 -mode out_of_context
write_checkpoint -noxdef top.dcp
catch { report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb }
