# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/Users/TEMP/Desktop/keremlab2/keremlab2.cache/wt [current_project]
set_property parent.project_path D:/Users/TEMP/Desktop/keremlab2/keremlab2.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib -sv D:/Users/TEMP/Desktop/keremlab2/keremlab2.srcs/sources_1/new/decoder24.sv
read_xdc D:/Users/TEMP/Desktop/keremlab2/keremlab2.srcs/constrs_1/new/keremlab2.xdc
set_property used_in_implementation false [get_files D:/Users/TEMP/Desktop/keremlab2/keremlab2.srcs/constrs_1/new/keremlab2.xdc]

synth_design -top decoder24 -part xc7a35tcpg236-1
write_checkpoint -noxdef decoder24.dcp
catch { report_utilization -file decoder24_utilization_synth.rpt -pb decoder24_utilization_synth.pb }
