default: alignSeqToProfile

alignSeqToProfile.o: alignSeqToProfile.c $(HEADERS)
	gcc -c alignSeqToProfile.c -o alignSeqToProfile.o

alignSeqToProfile: alignSeqToProfile.o
	gcc alignSeqToProfile.o -o alignSeqToProfile