# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
debug::add_scope template.lib 1
set_msg_config -id {Common-41} -limit 4294967295
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/Users/TEMP/Desktop/Lab5/Lab5.cache/wt [current_project]
set_property parent.project_path D:/Users/TEMP/Desktop/Lab5/Lab5.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib -sv {
  D:/Users/TEMP/Desktop/Lab5/Lab5.srcs/sources_1/new/ClockDivider.sv
  D:/Users/TEMP/Desktop/Lab5/Lab5.srcs/sources_1/new/MotorDriver.sv
  D:/Users/TEMP/Desktop/Lab5/Lab5.srcs/sources_1/new/SevSeg_4digit.sv
  D:/Users/TEMP/Desktop/Lab5/Lab5.srcs/sources_1/new/Car.sv
}
read_xdc D:/Users/TEMP/Desktop/Lab5/Lab5.srcs/constrs_1/new/CarCons.xdc
set_property used_in_implementation false [get_files D:/Users/TEMP/Desktop/Lab5/Lab5.srcs/constrs_1/new/CarCons.xdc]

synth_design -top Car -part xc7a35tcpg236-1
write_checkpoint -noxdef Car.dcp
catch { report_utilization -file Car_utilization_synth.rpt -pb Car_utilization_synth.pb }
