# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/Users/TEMP.PCLABS/Desktop/PipelinedProcessor/PipelinedProcessor.cache/wt [current_project]
set_property parent.project_path D:/Users/TEMP.PCLABS/Desktop/PipelinedProcessor/PipelinedProcessor.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths f:/LAB44444/Lab4/Lab4/MIPS/MIPS.cache/ip [current_project]
set_property ip_output_repo f:/LAB44444/Lab4/Lab4/MIPS/MIPS.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib -sv {
  D:/Users/TEMP.PCLABS/Desktop/PipelinedProcessor/PipelinedProcessor.srcs/sources_1/new/TopFinal.sv
  D:/Users/TEMP.PCLABS/Desktop/PipelinedProcessor/PipelinedProcessor.srcs/sources_1/new/pulse_controller.sv
  D:/Users/TEMP.PCLABS/Desktop/PipelinedProcessor/PipelinedProcessor.srcs/sources_1/new/display_controller.sv
  D:/Users/TEMP.PCLABS/Desktop/PipelinedProcessor/PipelinedProcessor.srcs/sources_1/new/pipeRegister.sv
  D:/Users/TEMP.PCLABS/Desktop/PipelinedProcessor/PipelinedProcessor.srcs/sources_1/new/datapath.sv
  D:/Users/TEMP.PCLABS/Desktop/PipelinedProcessor/PipelinedProcessor.srcs/sources_1/new/controller.sv
  D:/Users/TEMP.PCLABS/Desktop/PipelinedProcessor/PipelinedProcessor.srcs/sources_1/new/dmem.sv
  D:/Users/TEMP.PCLABS/Desktop/PipelinedProcessor/PipelinedProcessor.srcs/sources_1/new/imem.sv
  D:/Users/TEMP.PCLABS/Desktop/PipelinedProcessor/PipelinedProcessor.srcs/sources_1/new/mips.sv
  D:/Users/TEMP.PCLABS/Desktop/PipelinedProcessor/PipelinedProcessor.srcs/sources_1/new/top.sv
  D:/Users/TEMP.PCLABS/Desktop/PipelinedProcessor/PipelinedProcessor.srcs/sources_1/new/hazard.sv
}
read_xdc D:/Users/TEMP.PCLABS/Desktop/PipelinedProcessor/PipelinedProcessor.srcs/constrs_1/new/constraint.xdc
set_property used_in_implementation false [get_files D:/Users/TEMP.PCLABS/Desktop/PipelinedProcessor/PipelinedProcessor.srcs/constrs_1/new/constraint.xdc]

synth_design -top TopFinal -part xc7a35tcpg236-1
write_checkpoint -noxdef TopFinal.dcp
catch { report_utilization -file TopFinal_utilization_synth.rpt -pb TopFinal_utilization_synth.pb }
